- name: "add group hosts to /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ hostvars[item]['inventory_hostname'] }}(\\s*)$"
    line: "{{ hostvars[item]['ansible_'+hostvars[item]['iface']]['ipv4']['address'] }}	{{ hostvars[item]['inventory_hostname'] }}"
  with_items: "{{ groups[group] }}"
